services:
  db:
    container_name: db_kavout_kazh
    image: postgres
    restart: always
    networks:
      - kavout
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kazh
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    container_name: kavout_kazh
    build: .
    networks:
      - kavout
    depends_on:
      - db
    ports:
      - 3000:3000

networks:
  kavout:
    driver: bridge
