services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cats

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 5432:5432

  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

    ports:
      - "3000:3000"
    depends_on:
      - db
